### ISSUE TITLE
Export is a PNG

### ISSUE THREAD

**Issue by joostiphone** [chris1111/OpenCanopy-Generator#1]
![9118799](https://github.com/chris1111/OpenCanopy-Generator/assets/16277235/79b71878-d967-46a3-9406-2fbf121262b4)

Hi Chris, 

I'm trying to convert the attached png file (which I locally named Background.png), but it exports it to a png instead of a icns. Has it something to do with the size of the image?

**Comment by chris1111** [comment]
Yea probably the size is to big then is not proportional of OC Opencanopy Icons
Refer to [this](https://github.com/chris1111/OpenCanopy-Generator#all-backgroundpng-size-for-oc-066-and-higher) to resize the image to the size of your screen

`EDIT * * *`
After Resizing and testing your image, no such issue here

![Screenshot 2023-09-11 at 05 00 52](https://github.com/chris1111/OpenCanopy-Generator/assets/6248794/aa018541-e8d4-4dbf-8768-f48164ee4350)
